# Generated by Django 3.0.6 on 2020-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=25)),
                ('offer_img', models.ImageField(upload_to='newoffer/')),
            ],
        ),
    ]
