# Generated by Django 3.0.6 on 2020-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
