# Generated by Django 3.0.6 on 2020-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0002_offers_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=20)),
                ('gallery_img', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
