# Generated by Django 3.0.6 on 2020-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0004_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('email_id', models.EmailField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('tot_people', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(unique=True)),
            ],
        ),
    ]
